# Generated by Django 6.0 on 2026-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_model_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="device_model_version",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="device_serial_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
