# Generated by Django 6.0 on 2026-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0008_receipt_payment_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="signature",
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
