# Generated by Django 6.0 on 2026-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0010_alter_receipt_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="credit_note_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="credit_note_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_credit_note",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
