# Generated by Django 6.0 on 2026-01-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0003_device_production"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="device_model_number",
            new_name="device_model_name",
        ),
    ]
