# Generated by Django 6.0 on 2026-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0004_rename_device_model_number_device_device_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="certs",
            name="csr",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
