# Generated by Django 6.0 on 2026-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0005_certs_csr"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="zimra_inv_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
