# Generated by Django 6.0 on 2026-01-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0006_receipt_zimra_inv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptline",
            name="tax_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fiscguy.taxes",
            ),
        ),
    ]
