# Generated by Django 6.0 on 2026-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0007_alter_receiptline_tax_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="payment_terms",
            field=models.CharField(default="cash", max_length=200),
            preserve_default=False,
        ),
    ]
