# Generated by Django 6.0 on 2026-01-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0009_receipt_submitted_alter_receipt_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="submitted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
