# Generated by Django 6.0.2 on 2026-02-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phonenumber", models.CharField(max_length=20)),
                ("trade_name", models.CharField(max_length=100)),
                ("tin_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Certs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("csr", models.TextField()),
                ("certificate", models.TextField()),
                ("certificate_key", models.TextField()),
                ("production", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tax_payer_name", models.CharField(max_length=255)),
                ("tax_inclusive", models.BooleanField(default=True)),
                ("tin_number", models.CharField(max_length=20)),
                ("vat_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("org_name", models.CharField(max_length=255)),
                ("activation_key", models.CharField(max_length=255)),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("device_model_name", models.CharField(max_length=255, null=True)),
                ("device_serial_number", models.CharField(max_length=255, null=True)),
                ("device_model_version", models.CharField(max_length=255, null=True)),
                ("production", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FiscalDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_no", models.IntegerField()),
                ("receipt_counter", models.IntegerField()),
                ("is_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Taxes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("tax_id", models.IntegerField()),
                ("percent", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FiscalCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fiscal_counter_type",
                    models.CharField(
                        choices=[
                            ("SaleByTax", "Sale_by_Tax"),
                            ("SaleTaxByTax", "Sale Tax by Tax"),
                            ("CreditNoteByTax", "Credit Note by Tax"),
                            ("CreditNoteTaxByTax", "Credit Note Tax by Tax"),
                            ("DebitNoteByTax", "Debit Note by Tax"),
                            ("DebitNoteTaxByTax", "Debit Note Tax by Tax"),
                            ("BalanceByMoneyType", "Balance by Money Type"),
                            ("Other", "Other"),
                        ],
                        default="SaleByTax",
                        max_length=30,
                    ),
                ),
                (
                    "fiscal_counter_currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("ZWG", "zwg")], default="USD", max_length=10
                    ),
                ),
                (
                    "fiscal_counter_tax_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
                    ),
                ),
                ("fiscal_counter_tax_id", models.IntegerField(default=3)),
                (
                    "fiscal_counter_money_type",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("BankTransfer", "Bank Transfer"),
                            ("MobileMoney", "Mobile Money"),
                        ],
                        default="Cash",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fiscal_counter_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fiscal_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="fiscguy.fiscalday",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("fiscalinvoice", "Fiscal Invoice"),
                            ("creditnote", "Creditnote"),
                            ("debitnote", "Debitnote"),
                        ],
                        default="fiscalinvoice",
                        max_length=255,
                    ),
                ),
                ("total_amount", models.FloatField()),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="Zimra_qr_codes")),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "usd"), ("ZWG", "zwg")], default="USD", max_length=255
                    ),
                ),
                ("global_number", models.IntegerField(blank=True, null=True)),
                ("hash_value", models.CharField(blank=True, max_length=255, null=True)),
                ("signature", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("zimra_inv_id", models.CharField(max_length=255, null=True)),
                ("payment_terms", models.CharField(max_length=200)),
                ("submitted", models.BooleanField(default=False, null=True)),
                ("is_credit_note", models.BooleanField(default=False, null=True)),
                ("credit_note_reason", models.CharField(blank=True, max_length=255, null=True)),
                ("credit_note_reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="fiscguy.buyer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("line_total", models.FloatField()),
                ("tax_amount", models.FloatField()),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="fiscguy.receipt",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="fiscguy.taxes"
                    ),
                ),
            ],
        ),
    ]
