# Generated by Django 6.0.2 on 2026-02-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="trade_name",
        ),
    ]
