# Generated by Django 5.2 on 2026-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="payment_terms",
        ),
        migrations.AddField(
            model_name="receipt",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Card", "Card"),
                    ("MobileWallet", "Mobile Wallet"),
                    ("BankTransfer", "Bank Transfer"),
                    ("Coupon", "Coupon"),
                    ("Credit", "Credit"),
                    ("Other", "Other"),
                ],
                default="Cash",
                max_length=20,
            ),
        ),
    ]
