# Generated by Django 6.0.2 on 2026-02-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0002_remove_buyer_email_remove_buyer_phonenumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="email",
            field=models.EmailField(default="cas@s.com", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="phonenumber",
            field=models.CharField(default="2", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="trade_name",
            field=models.CharField(default="s", max_length=100),
            preserve_default=False,
        ),
    ]
