# Generated by Django 6.0 on 2026-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0002_device_device_model_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="production",
            field=models.BooleanField(default=False),
        ),
    ]
