# Generated by Django 5.2 on 2026-03-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0002_remove_receipt_payment_terms_receipt_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="payment_method",
            new_name="payment_terms",
        ),
    ]
