# Generated by Django 5.2 on 2026-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0003_rename_payment_method_receipt_payment_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalcounter",
            name="fiscal_counter_tax_id",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
