# Generated by Django 5.2 on 2026-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0004_alter_fiscalcounter_fiscal_counter_tax_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(max_length=100),
        ),
    ]
