# Generated by Django 5.2 on 2026-04-01 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0005_alter_device_device_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="certs",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="configuration",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="fiscalcounter",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="fiscalday",
            options={"ordering": ["-day_no"]},
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="receiptline",
            options={"ordering": ["receipt", "id"]},
        ),
        migrations.AlterModelOptions(
            name="taxes",
            options={"ordering": ["tax_id"], "verbose_name_plural": "Taxes"},
        ),
        migrations.AddField(
            model_name="buyer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="certs",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certs",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="fiscguy.device",
            ),
        ),
        migrations.AddField(
            model_name="certs",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="configuration",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuration",
                to="fiscguy.device",
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fiscalcounter",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal_counters",
                to="fiscguy.device",
            ),
        ),
        migrations.AddField(
            model_name="fiscalcounter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiscal_days",
                to="fiscguy.device",
            ),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="fiscguy.device",
            ),
        ),
        migrations.AddField(
            model_name="receiptline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receiptline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="taxes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyer",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="trade_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_model_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_model_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_serial_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fiscalday",
            name="receipt_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="zimra_inv_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receiptline",
            name="tax_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiscguy.taxes",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalday",
            unique_together={("device", "day_no")},
        ),
        migrations.AddIndex(
            model_name="buyer",
            index=models.Index(fields=["tin_number"], name="fiscguy_buy_tin_num_b1f84c_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="fiscguy_dev_device__b5971a_idx"),
        ),
        migrations.AddIndex(
            model_name="fiscalcounter",
            index=models.Index(
                fields=["device", "fiscal_day"], name="fiscguy_fis_device__5b810d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalday",
            index=models.Index(fields=["device", "is_open"], name="fiscguy_fis_device__8563f5_idx"),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["receipt_number"], name="fiscguy_rec_receipt_cdbc56_idx"),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["device", "-created_at"], name="fiscguy_rec_device__ab056a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiptline",
            index=models.Index(fields=["receipt"], name="fiscguy_rec_receipt_938793_idx"),
        ),
        migrations.AddIndex(
            model_name="taxes",
            index=models.Index(fields=["tax_id"], name="fiscguy_tax_tax_id_48ddeb_idx"),
        ),
    ]
