# Generated by Django 5.2 on 2026-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0006_alter_buyer_options_alter_certs_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptline",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
