# Generated by Django 5.2 on 2026-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0007_alter_receiptline_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receiptline",
            name="line_total",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receiptline",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="receiptline",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="receiptline",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="taxes",
            name="percent",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
