# Generated by Django 5.2 on 2026-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0008_alter_receipt_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="certificate_valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="device_operating_mode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="configuration",
            name="tax_payer_day_end_notification_hrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="tax_payer_day_max_hrs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
