# Generated by Django 5.2 on 2026-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscguy", "0009_configuration_fdms_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="close_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="close_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="close_state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("close_pending", "Close Pending"),
                    ("close_failed", "Close Failed"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="fdms_status",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="last_close_error_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="fiscalday",
            name="last_status_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
