# Generated by Django 6.0.2 on 2026-05-03

from django.db import migrations

import fiscguy.fields
from fiscguy.security import decrypt_value, encrypt_value


def encrypt_existing_certificate_keys(apps, schema_editor):
    Certs = apps.get_model("fiscguy", "Certs")
    for cert_id, certificate_key in Certs.objects.values_list("id", "certificate_key"):
        if certificate_key:
            Certs.objects.filter(id=cert_id).update(certificate_key=encrypt_value(certificate_key))


def decrypt_existing_certificate_keys(apps, schema_editor):
    Certs = apps.get_model("fiscguy", "Certs")
    for cert_id, certificate_key in Certs.objects.values_list("id", "certificate_key"):
        if certificate_key:
            Certs.objects.filter(id=cert_id).update(certificate_key=decrypt_value(certificate_key))


class Migration(migrations.Migration):
    dependencies = [
        ("fiscguy", "0010_fiscalday_close_state_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certs",
            name="certificate_key",
            field=fiscguy.fields.EncryptedTextField(),
        ),
        migrations.RunPython(
            encrypt_existing_certificate_keys,
            reverse_code=decrypt_existing_certificate_keys,
        ),
    ]
