# Generated by Django 6.0.2 on 2026-05-03

from django.db import migrations, models


def backfill_tax_device(apps, schema_editor):
    Device = apps.get_model("fiscguy", "Device")
    Taxes = apps.get_model("fiscguy", "Taxes")

    device = Device.objects.order_by("id").first()
    if not device:
        return

    Taxes.objects.filter(device__isnull=True).update(device=device)


class Migration(migrations.Migration):
    dependencies = [
        ("fiscguy", "0011_encrypt_certificate_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxes",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="taxes",
                to="fiscguy.device",
            ),
        ),
        migrations.RunPython(backfill_tax_device, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="taxes",
            index=models.Index(fields=["device", "tax_id"], name="fiscguy_tax_device__fb41cc_idx"),
        ),
    ]
