# Generated by Django 6.0.2 on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fiscguy", "0012_taxes_device_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptline",
            name="hs_code",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
